// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class Category
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ParentCategoryId { get; set; }

    public string CategoryImage { get; set; }

    public string CategoryUrl { get; set; }

    public int SortOrder { get; set; }
}