// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class Coupon
{
    public Guid Id { get; set; }

    public string CouponCode { get; set; }

    public double? DiscountPercentage { get; set; }
}