// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class Item
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string CategoryId { get; set; }

    public double Price { get; set; }

    public int Quantity { get; set; }

    public int? SortOrder { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<ItemVisual> ItemVisuals { get; set; } = new List<ItemVisual>();

    public virtual ICollection<OrderLine> OrderLines { get; set; } = new List<OrderLine>();
}