// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class ItemVisual
{
    public Guid Id { get; set; }

    public Guid ItemId { get; set; }

    public string ImgUrl { get; set; }

    public bool? IsMain { get; set; }

    public virtual Item Item { get; set; }
}