// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class OrderLine
{
    public Guid Id { get; set; }

    public string ItemName { get; set; }

    public Guid ItemId { get; set; }

    public double Price { get; set; }

    public int Quantity { get; set; }

    public string OrderHeaderId { get; set; }

    public virtual Item Item { get; set; }
}