// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class OrderHeader
{
    public Guid Id { get; set; }

    public int TotalItems { get; set; }

    public double TotalPrice { get; set; }

    public Guid UserId { get; set; }

    public DateTimeOffset? CreatedDate { get; set; }

    public bool IsDiscountApplied { get; set; }

    public virtual User User { get; set; }
}