// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Commerce.API.Models;

public partial class Review
{
    public Guid Id { get; set; }

    public string UserId { get; set; }

    public string ReviewMessage { get; set; }
}